name: Deploy Backend to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add VPS Host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: |
          rsync -az --delete --exclude=".git*" --exclude="node_modules" ./ root@${{ secrets.SERVER_IP }}:/home/pdfbackend

      - name: Install dependencies & restart backend
        run: |
          ssh root@${{ secrets.SERVER_IP }} << 'EOF'
            cd /home/pdfbackend
            npm install --production
            pm2 restart pdfviewerbe || pm2 start server.js --name pdfviewerbe
            pm2 save
          EOF
